Added "albumId" to "getPhotos" options
esteban-uo/picasa pull request #6
Opened 2016-10-07 08:19 UTC by z1c0

The "options" object passed to "getPhotos" now looks for an "albumId" property and retrieves only photos for this specific album.

Updated sample code.

2016-10-08 10:40 UTC, esteban-uo commented
@z1c0 thanks!, your commit is behind master and is causing the conflict with your previous PR, could you please update it?

2016-10-08 10:43 UTC, esteban-uo commented on src/picasa.js
nice option!, can we apply it in this way?

```js
const albumPart = options.albumId ? `/albumid/${options.albumId}` : '';
```

2016-10-08 10:45 UTC, esteban-uo requested changes
Just need to update a small style code suggestion & merge conflict

2016-10-08 14:07 UTC, closed without merging

2017-05-12 14:16 UTC, hbakhtiyor commented
@esteban-uo why not merged?

2017-05-13 16:10 UTC, esteban-uo commented
@hbakhtiyor I missed the notification, thanks for the reminder. And sorry @z1c0 and thanks!

2017-05-13 16:11 UTC, esteban-uo reviewed
Approved. But seems to be that @z1c0 fork was deleted and I can't merge the PR. I'm going to add it by myself next week.

2017-05-16 20:32 UTC, esteban-uo commented
@z1c0 merged, thanks for your PR and thx @hbakhtiyor for the reminder